import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "react-datepicker/dist/react-datepicker.css";
import Header from "./components/Header";
import { AppDataProvider } from "./context/AppDataContext"; // ✅ import context provider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Appointment Booking",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ Wrap entire app inside the provider */}
        <AppDataProvider>
          <Header />
          <main className="pt-[70px]"> {/* optional padding for fixed header */}
            {children}
          </main>
        </AppDataProvider>
      </body>
    </html>
  );
}
